# Generated by Django 5.1.2 on 2024-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toybos_products', '0002_alter_product_options_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
