# Generated by Django 5.1.2 on 2024-10-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toybos_products', '0004_product_ingredients_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Ingredients',
            new_name='ingredients',
        ),
    ]
