# Generated by Django 5.1.2 on 2024-10-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toybos_products', '0005_rename_ingredients_product_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Публикации',
                'verbose_name_plural': 'Публикация',
            },
        ),
    ]
