# Generated by Django 5.1.2 on 2024-10-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toybos_products', '0008_publication_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
