# Generated by Django 5.0.6 on 2024-10-25 12:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toybos_products', '0009_aboutme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'О нас ', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AddField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
