# Generated by Django 5.0.6 on 2024-10-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toybos_products', '0010_alter_aboutme_options_aboutme_image_aboutme_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='image',
        ),
    ]
