# Generated by Django 5.1.2 on 2024-10-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toybos_products', '0012_recipes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'verbose_name': 'Рецепты ', 'verbose_name_plural': 'Рецепт'},
        ),
        migrations.AddField(
            model_name='recipes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
