# Generated by Django 5.1.2 on 2024-10-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toybos_products', '0013_alter_recipes_options_recipes_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='short_description',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
