# Generated by Django 5.1.2 on 2024-10-26 06:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toybos_products', '0014_aboutme_image_aboutme_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='directions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
