# Generated by Django 5.1.2 on 2024-10-26 06:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toybos_products', '0015_recipes_directions_recipes_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='directions',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
