# Generated by Django 5.1.2 on 2024-10-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toybos_products', '0016_alter_recipes_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='products',
            field=models.ManyToManyField(related_name='recipes', to='toybos_products.product'),
        ),
    ]
