# Generated by Django 5.1.2 on 2024-10-26 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toybos_products', '0017_recipes_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
            ],
            options={
                'verbose_name': 'Социальные сети и контакт',
                'verbose_name_plural': 'Социальные сети и контакт',
            },
        ),
    ]
