# Generated by Django 5.1.2 on 2024-10-27 11:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toybos_products', '0018_socialmediacontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='short_description_en',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='short_description_ru',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='short_description_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='short_description_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='directions_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='directions_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
