# Generated by Django 5.1.2 on 2024-10-28 13:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toybos_products', '0019_aboutme_description_en_aboutme_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='description_kz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='short_description_ky',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='short_description_kz',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='title_ky',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='title_kz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_kz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='short_description_ky',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='short_description_kz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ky',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_kz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='description_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='directions_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='directions_kz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients_kz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='title_ky',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='title_kz',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
