# Generated by Django 5.1.2 on 2024-10-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toybos_products', '0021_rename_description_kz_aboutme_description_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(default='хорошоя колбаса'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_en',
            field=models.TextField(default='хорошоя колбаса', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_kk',
            field=models.TextField(default='хорошоя колбаса', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_ky',
            field=models.TextField(default='хорошоя колбаса', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_ru',
            field=models.TextField(default='хорошоя колбаса', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(default='/media/post-5_A8VoxH3.jpeg/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(default='колбаса', max_length=250),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_en',
            field=models.CharField(default='колбаса', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_kk',
            field=models.CharField(default='колбаса', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_ky',
            field=models.CharField(default='колбаса', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_ru',
            field=models.CharField(default='колбаса', max_length=250, null=True),
        ),
    ]
